# Generated by Django 5.0.2 on 2024-04-18 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_shippingaddress_shipping_address2_oreder_and_more'),
        ('store', '0005_profile_old_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oreder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrerItem',
            new_name='OrderItem',
        ),
    ]
